# Generated by Django 4.1.4 on 2022-12-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
