# Generated by Django 4.1.4 on 2022-12-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0002_remove_user_address_remove_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
            ],
        ),
    ]
