# Generated by Django 4.1.4 on 2022-12-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0003_registration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
